GET http://localhost:4000/

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"alyaa",
    "password": "12345"
    
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "username":"alyaa",
    "password": "12345",
    "email": "yaya@gmail.com"

}